application: contest-twitter-mn
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: myproject.wsgi.application

libraries:
- name: django
  version: 1.5
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest