application: contest-twitter-mn
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static/
- url: /tweetEvening
  script: ContestTweets.wsgi.application
  login: admin
- url: /tweetMorning
  script: ContestTweets.wsgi.application
  login: admin
- url: /tweetAlways
  script: ContestTweets.wsgi.application
  login: admin
- url: .*
  script: ContestTweets.wsgi.application

libraries:
- name: django
  version: 1.5
- name: ssl
  version: latest
